package org.formation.dao;


import org.formation.model.CompteBancaire;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * The implementation of interface is not required It is generated by Spring
 * Data JPA Framework This interface is responsible for CRUD + custom queries
 * based on query methods and parameter name and types
 */
public interface CrudCompteDao extends JpaRepository<CompteBancaire, Integer> {

	// customized methods here

	
}
